mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('polls.urls')),
]

mysite/polls/urls.py
from django.urls import path
from . import views

# namespacing the urls.py of polls app for use in template links
app_name = 'polls'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('pollsindex/', views.PollsIndexView.as_view(), name='pollsindex'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

mysite/polls/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.contrib import admin

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=255)
    pub_date = models.DateTimeField('date published', default=timezone.now)

    def __str__(self):
        return self.question_text

    # wrapper to format was_published_recently in admin view
    @admin.display(
        boolean=True,
        ordering='pub_date',
        description='Published Recently'
    )
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

mysite/polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic
from .models import Question, Choice
from django.utils import timezone

class IndexView(generic.TemplateView):
    template_name = 'polls/index.html'

class PollsIndexView(generic.ListView):
    template_name = 'polls/pollsindex.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return last five published questions
        """
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        """
        Excludes any questions with pub_date > timezone.now()
        """
        return Question.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    # attempt to fetch question
    question = get_object_or_404(Question, pk=question_id)
    try:
        # get selected choice from the question via post data
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # if posted without a choice then render detail page with error message
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice"
        })
    else:
        # incremenet the choice by 1
        selected_choice.votes += 1
        selected_choice.save()
        # redirect after successful post
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

mysite/polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    
    {% load static %}

    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'polls/style.css' %}"
    />

    <title>Polls App - Question</title>
  </head>
  <body>
    <form action="{% url 'polls:vote' question.id %}" method="post">
      {% csrf_token %}
      <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
        {% endif %} {% for choice in question.choice_set.all %}
        <input
          type="radio"
          name="choice"
          id="choice{{ forloop.counter }}"
          value="{{ choice.id }}"
        />
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label
        ><br />
        {% endfor %}
      </fieldset>
      <input type="submit" value="Vote" />
    </form><br>
    <a href="{% url 'polls:pollsindex' %}">Go home</a>
  </body>
</html>

mysite/polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    {% load static %}

    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'polls/style.css' %}"
    />

    <title>Polls App - Index</title>
  </head>
  <body>
  <h1>Django Tutorial: Polling App</h1>
    <h3>What is this app?</h3>
    <p>
      This is a simple demonstration of my completion of
      <a
        link
        target="_blank"
        href="https://docs.djangoproject.com/en/3.2/intro/tutorial01/"
        >the official django introduction tutorial</a
      >.
    </p>
    <h3>What I learnt</h3>
    <ul>
      <li>Creating django projects & apps</li>
      <li>Implementing custom templates & styling</li>
      <li>Creating models, views and routes</li>
      <li>Working with jinja templating</li>
      <li>Ensuring scalability of app design</li>
      <li>Writing effective tests on models and views</li>
      <li>Customising the admin dashboard</li>
    </ul>
    <h3>Other web-related subjects I know but did not demonstrate here</h3>
    <ul>
      <li>JavaScript</li>
      <li>React</li>
      <li>Flask and Flask API</li>
      <li>Web pack / Babel</li>
      <li>Firebase</li>
      <li>Parse Server</li>
      <li>MongoDB</li>
      <li>PostgreSQL</li>
    </ul>
    <h3>Get in touch</h3>
    <ul>
      <li><a href="https://www.linkedin.com/in/paulwilson888/">https://www.linkedin.com/in/paulwilson888/</a></li>
    </ul>
    <a class="a_large" link href="{% url 'polls:pollsindex' %}">Go to app</a>
  </body>
</html>

mysite/polls/templates/polls/pollsindex.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    {% load static %}

    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'polls/style.css' %}"
    />

    <title>Polls App - Index</title>
  </head>
  <body>
  <h1>Available Polls</h1>
  <a link href="{% url 'polls:index' %}">Back to homepage</a><br>

  <a class="a_large" link href="/admin">Login to custom admin site (admin, admin)</a>

    {% if latest_question_list %}
    <h3>Available Polls</h3>
    <ul>
      {% for question in latest_question_list %}
      <li>
        <a href="{% url 'polls:detail' question.id %}"
          >{{ question.question_text }}</a
        >
      </li>
      {% endfor %}
    </ul>
    {% else %}
    <h3>No polls are available.</h3>
    {% endif %}
  </body>
</html>

mysite/polls/templates/polls/results.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    {% load static %}

    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'polls/style.css' %}"
    />

    <title>Polls App - Results</title>
  </head>
  <body>
    <h1>{{ question.question_text }}</h1>

    <ul>
      {% for choice in question.choice_set.all %}
      <li>
        {{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}
      </li>
      {% endfor %}
    </ul>

    <a href="{% url 'polls:detail' question.id %}">Vote again?</a>
    <br>
    <a href="{% url 'polls:pollsindex' %}">Go home</a>
  </body>
</html>